#!/usr/bin/python

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Author: Mariano Simone (marianosimone@gmail.com)
# Version: 1.0
# Name: epub-thumbnailer
# Description: An implementation of a cover thumbnailer for epub files
# Installation: see README

import zipfile
import sys
import Image
import shutil
import os
import re

# Which file are we working with?
input_file = sys.argv[1]
# Where do does the file have to be saved?
output_file = sys.argv[2]
# Required size?
size = int(sys.argv[3])

# An epub is just a zip
epub = zipfile.ZipFile(input_file, "r")

# Just some examples of what I found inside my epubs...
# FIXME: Still can find some false positives. Maybe we can get all, and rank solutions
cover_regex = re.compile(".*cover.*\.(jpg|png)")

for fileinfo in epub.filelist:
    try:
        if cover_regex.match(os.path.basename(fileinfo.filename).lower()):
            epub.extract(fileinfo, "/tmp")
            tmp_cover_path = os.path.join("/tmp", fileinfo.filename)
            im = Image.open(tmp_cover_path)
            im.thumbnail((size, size), Image.ANTIALIAS)
            im.save(output_file, "PNG")
            if "/" in fileinfo.filename: # cover was inside a dir
                shutil.rmtree(os.path.join("/tmp", fileinfo.filename.split("/")[0]))
            else: # or just in the epub's root
                os.remove(tmp_cover_path)
            exit(0)
    except Exception as ex:
        print "Couldn't make thumbnail using: ", fileinfo.filename, ex

exit(1)
